function cellInfo = l180_bus(varargin) 
% L180_BUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'slBus12', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'Ground_Speed', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Steering_Angle', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Wheel_Speed_Yaw_Rate', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Acceleration_Y_Filt', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
