function cellInfo = vehicleBus(varargin) 
% VEHICLEBUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'slBus100_rocker', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'damperPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus102_upright', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'wheelCenterDelta2KPI', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rotationAxisOne', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rotationAxisTwo', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelAxleOffsetToUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterPlaneAlongUBJ2LBJAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus103_lowerAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus104_chassis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus105_Pot', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'pivotPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'armPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'shaftAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus108_upperAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'UBJ_UPRIGHT_POS_1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pivotPart', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus109_steeringRack', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus10_damper', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'fittedLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxCompression', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxDroop', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassisPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus110_ARB', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'torsionBarEnd', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkConnection', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkRotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkHole', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkRotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkHole', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkAArm', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus111_front', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'tyreCorneringStiffness', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyrecenterPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryInside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryOutside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreRadius', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreWidth', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CentreLineLaser', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationLeft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationRight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevis', 1, 'slBus95_clevis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damper', 1, 'slBus97_damper', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rocker', 1, 'slBus100_rocker', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upright', 1, 'slBus102_upright', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lowerAArm', 1, 'slBus103_lowerAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassis', 1, 'slBus104_chassis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pot', 1, 'slBus105_Pot', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upperAArm', 1, 'slBus108_upperAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'steeringRack', 1, 'slBus109_steeringRack', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ARB', 1, 'slBus110_ARB', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus112_kinematics', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'body', 1, 'slBus83_body', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rear', 1, 'slBus94_rear', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'front', 1, 'slBus111_front', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus113_steering', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ratio', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus114_teamData', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'IMU', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus115_sensors', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'teamData', 1, 'slBus114_teamData', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus116_bicycleModel', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'FrontTrackLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RearTrackLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'totalMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontAxleMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearAxleMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CoGLocation', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontArm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearArm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus117_toyota', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'kinematics', 1, 'slBus112_kinematics', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'steering', 1, 'slBus113_steering', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'sensors', 1, 'slBus115_sensors', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'minimumWheelbase', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumWheelbase', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumTrackWidthFront', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumTrackWidthRear', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontAxleBodyWorkMaximum', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearAxleBodyWorkMaximum', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofHeight_neg510mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_neg290mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_pos305', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontBumperLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearBumperLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingPivotPointX', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingPivotPointZ', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingElementDimensions', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingAngleMin', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingAngleMax', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingToDecklidSpoilerSpacingMax', [2 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1500', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1950', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2400', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2800', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bootLidHeight_pos1290', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bootLidHeight_pos1675', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dashHeight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelArchLinersFront', [1 1], 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelArchLinersRear', [1 1], 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bicycleModel', 1, 'slBus116_bicycleModel', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofHeight_neg630mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_neg235_5mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_pos448', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_mm_0', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_mm_80', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_mm_160', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_deg_0', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_deg_80', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_deg_160', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1550', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2206', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2500', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2750', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1397', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1675', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus118_body', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'CoG', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'trackWidth', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus119_clevis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'POS1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'yOffset', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus11_Pot', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'pivotPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'armPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'shaftAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus122_upperAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'UBJ_UPRIGHT_POS_1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightConnector', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightBalljointAdjust', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJointCAD', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus123_damper', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'fittedLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxCompression', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxDroop', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassisPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus124_Pot', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'pivotPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'armPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'shaftAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus125_rocker', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ARBPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damperPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus126_lowerAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus127_chassis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus128_upright', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'rotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterPlaneAlongUBJ2LBJAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterDelta2KPI', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelAxleOffsetToUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelMatingFace2RotatationalAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus129_rear', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'tyreCorneringStiffness', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyrecenterPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryInside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryOutside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreRadius', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreWidth', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CentreLineLaser', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationLeft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationRight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevis', 1, 'slBus119_clevis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upperAArm', 1, 'slBus122_upperAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damper', 1, 'slBus123_damper', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pot', 1, 'slBus124_Pot', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rocker', 1, 'slBus125_rocker', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lowerAArm', 1, 'slBus126_lowerAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassis', 1, 'slBus127_chassis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upright', 1, 'slBus128_upright', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus12_rocker', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ARBPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damperPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus130_clevis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'POS1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'yOffset', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus131_damper', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'chassisPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fittedLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxCompression', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxDroop', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus132_rocker', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'damperPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus133_upright', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'wheelCenterDelta2KPI', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rotationAxisOne', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rotationAxisTwo', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelAxleOffsetToUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterPlaneAlongUBJ2LBJAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus134_lowerAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus135_chassis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus136_Pot', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'pivotPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'armPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'shaftAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus137_upperAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'UBJ_UPRIGHT_POS_1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pivotPart', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus138_steeringRack', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus139_ARB', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'torsionBarEnd', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkConnection', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkRotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkHole', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkRotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkHole', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkAArm', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus13_lowerAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus140_front', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'tyreCorneringStiffness', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyrecenterPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryInside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryOutside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreRadius', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreWidth', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CentreLineLaser', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationLeft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationRight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevis', 1, 'slBus130_clevis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damper', 1, 'slBus131_damper', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rocker', 1, 'slBus132_rocker', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upright', 1, 'slBus133_upright', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lowerAArm', 1, 'slBus134_lowerAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassis', 1, 'slBus135_chassis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pot', 1, 'slBus136_Pot', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upperAArm', 1, 'slBus137_upperAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'steeringRack', 1, 'slBus138_steeringRack', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ARB', 1, 'slBus139_ARB', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus141_kinematics', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'body', 1, 'slBus118_body', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rear', 1, 'slBus129_rear', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'front', 1, 'slBus140_front', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus142_steering', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ratio', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus143_teamData', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'IMU', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus144_sensors', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'teamData', 1, 'slBus143_teamData', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus145_bicycleModel', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'FrontTrackLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RearTrackLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'totalMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontAxleMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearAxleMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CoGLocation', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontArm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearArm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus146_chevrolet', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'kinematics', 1, 'slBus141_kinematics', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'steering', 1, 'slBus142_steering', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'sensors', 1, 'slBus144_sensors', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'minimumWheelbase', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumWheelbase', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumTrackWidthFront', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumTrackWidthRear', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontAxleBodyWorkMaximum', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearAxleBodyWorkMaximum', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofHeight_neg510mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_neg290mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_pos305', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontBumperLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearBumperLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingPivotPointX', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingPivotPointZ', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingElementDimensions', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingAngleMin', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingAngleMax', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingToDecklidSpoilerSpacingMax', [2 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1500', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1950', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2400', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2800', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bootLidHeight_pos1290', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bootLidHeight_pos1675', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dashHeight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelArchLinersFront', [1 1], 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelArchLinersRear', [1 1], 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bicycleModel', 1, 'slBus145_bicycleModel', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofHeight_neg625mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_neg224_1mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_pos605mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_mm_0', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_mm_TBA1', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_mm_TBA2', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_deg_0', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_deg_TBA1', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_deg_TBA2', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1595', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2170', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2425', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2740', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1397', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1675', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus147', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ford', 1, 'slBus41_ford', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'kinematics', 1, 'slBus44_kinematics', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Chevrolet', 1, 'slBus82_Chevrolet', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toyota', 1, 'slBus117_toyota', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chevrolet', 1, 'slBus146_chevrolet', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus14_chassis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus16_upright', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'rotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterPlaneAlongUBJ2LBJAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterDelta2KPI', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelAxleOffsetToUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelMatingFace2RotatationalAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus17_rear', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'tyreCorneringStiffness', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyrecenterPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryInside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryOutside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreRadius', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreWidth', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CentreLineLaser', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationLeft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationRight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevis', 1, 'slBus7_clevis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upperAArm', 1, 'slBus9_upperAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damper', 1, 'slBus10_damper', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pot', 1, 'slBus11_Pot', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rocker', 1, 'slBus12_rocker', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lowerAArm', 1, 'slBus13_lowerAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassis', 1, 'slBus14_chassis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upright', 1, 'slBus16_upright', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus18_clevis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'POS1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'yOffset', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus20_damper', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'chassisPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fittedLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxCompression', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxDroop', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus22_rocker', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'damperPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus24_upright', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'wheelCenterDelta2KPI', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rotationAxisOne', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rotationAxisTwo', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelAxleOffsetToUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterPlaneAlongUBJ2LBJAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus25_lowerAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus26_chassis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus27_Pot', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'pivotPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'armPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'shaftAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus28_upperAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'UBJ_UPRIGHT_POS_1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pivotPart', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus29_steeringRack', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus30_ARB', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'torsionBarEnd', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkConnection', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkRotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkHole', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkRotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkHole', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkAArm', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus34_front', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'tyreCorneringStiffness', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyrecenterPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryInside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryOutside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreRadius', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreWidth', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CentreLineLaser', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationLeft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationRight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevis', 1, 'slBus18_clevis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damper', 1, 'slBus20_damper', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rocker', 1, 'slBus22_rocker', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upright', 1, 'slBus24_upright', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lowerAArm', 1, 'slBus25_lowerAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassis', 1, 'slBus26_chassis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pot', 1, 'slBus27_Pot', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upperAArm', 1, 'slBus28_upperAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'steeringRack', 1, 'slBus29_steeringRack', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ARB', 1, 'slBus30_ARB', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus36_kinematics', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'body', 1, 'slBus6_body', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rear', 1, 'slBus17_rear', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'front', 1, 'slBus34_front', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus37_steering', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ratio', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus38_teamData', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'IMU', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus39_sensors', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'teamData', 1, 'slBus38_teamData', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus40_bicycleModel', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'FrontTrackLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RearTrackLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'totalMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontAxleMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearAxleMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CoGLocation', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontArm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearArm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus41_ford', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'kinematics', 1, 'slBus36_kinematics', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'steering', 1, 'slBus37_steering', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'sensors', 1, 'slBus39_sensors', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'minimumWheelbase', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumWheelbase', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumTrackWidthFront', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumTrackWidthRear', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontAxleBodyWorkMaximum', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearAxleBodyWorkMaximum', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofHeight_neg510mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_neg290mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_pos305', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontBumperLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearBumperLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingPivotPointX', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingPivotPointZ', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingElementDimensions', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingAngleMin', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingAngleMax', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingToDecklidSpoilerSpacingMax', [2 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1500', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1950', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2400', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2800', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bootLidHeight_pos1290', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bootLidHeight_pos1675', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dashHeight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelArchLinersFront', [1 1], 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelArchLinersRear', [1 1], 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bicycleModel', 1, 'slBus40_bicycleModel', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus42_front', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'camberShims_5219', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'camberShims_5220', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'camberShims_5221', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'camberShims_5222', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevisShims_5116', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevisShims_5129', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevisShims_5117', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevisShims_5118', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus43_rear', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'camberShims_3127', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'camberShims_3140', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'camberShims_3141', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'camberShims_CAD_ERROR', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevisShims_5116', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevisShims_5117', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevisShims_5118', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevisShims_5129', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus44_kinematics', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'front', 1, 'slBus42_front', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rear', 1, 'slBus43_rear', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus45_body', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'CoG', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'trackWidth', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus48_clevis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'POS1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'yOffset', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus49_upperAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'UBJ_UPRIGHT_POS_1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightConnector', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightBalljointAdjust', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJointCAD', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus51_damper', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'fittedLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxCompression', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxDroop', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassisPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus54_Pot', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'pivotPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'armPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'shaftAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus56_rocker', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ARBPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damperPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus58_lowerAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus59_chassis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus60_upright', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'rotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterPlaneAlongUBJ2LBJAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterDelta2KPI', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelAxleOffsetToUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelMatingFace2RotatationalAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus61_rear', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'tyreCorneringStiffness', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyrecenterPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryInside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryOutside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreRadius', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreWidth', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CentreLineLaser', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationLeft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationRight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevis', 1, 'slBus48_clevis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upperAArm', 1, 'slBus49_upperAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damper', 1, 'slBus51_damper', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pot', 1, 'slBus54_Pot', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rocker', 1, 'slBus56_rocker', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lowerAArm', 1, 'slBus58_lowerAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassis', 1, 'slBus59_chassis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upright', 1, 'slBus60_upright', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus62_clevis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'POS1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'yOffset', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus64_damper', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'chassisPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fittedLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxCompression', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxDroop', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus66_rocker', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'damperPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus67_upright', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'wheelCenterDelta2KPI', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rotationAxisOne', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rotationAxisTwo', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelAxleOffsetToUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterPlaneAlongUBJ2LBJAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus6_body', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'CoG', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'trackWidth', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus70_lowerAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus71_chassis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus72_Pot', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'pivotPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'armPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'shaftAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus73_upperAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'UBJ_UPRIGHT_POS_1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pivotPart', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus74_steeringRack', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus75_ARB', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'torsionBarEnd', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkConnection', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkRotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dropLinkHole', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkRotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkHole', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'transferLinkAArm', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus76_front', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'tyreCorneringStiffness', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyrecenterPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryInside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryOutside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreRadius', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreWidth', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CentreLineLaser', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationLeft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationRight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevis', 1, 'slBus62_clevis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damper', 1, 'slBus64_damper', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rocker', 1, 'slBus66_rocker', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upright', 1, 'slBus67_upright', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lowerAArm', 1, 'slBus70_lowerAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassis', 1, 'slBus71_chassis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pot', 1, 'slBus72_Pot', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upperAArm', 1, 'slBus73_upperAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'steeringRack', 1, 'slBus74_steeringRack', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ARB', 1, 'slBus75_ARB', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus77_kinematics', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'body', 1, 'slBus45_body', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rear', 1, 'slBus61_rear', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'front', 1, 'slBus76_front', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus78_steering', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ratio', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus79_teamData', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'IMU', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus7_clevis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'POS1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'yOffset', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus80_sensors', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'teamData', 1, 'slBus79_teamData', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus81_bicycleModel', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'FrontTrackLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RearTrackLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'totalMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontAxleMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearAxleMass', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CoGLocation', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontArm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearArm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus82_Chevrolet', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'kinematics', 1, 'slBus77_kinematics', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'steering', 1, 'slBus78_steering', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'sensors', 1, 'slBus80_sensors', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'minimumWheelbase', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumWheelbase', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumTrackWidthFront', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumTrackWidthRear', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maximumLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontAxleBodyWorkMaximum', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearAxleBodyWorkMaximum', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofHeight_neg510mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_neg290mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_pos305', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'frontBumperLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearBumperLocation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingPivotPointX', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingPivotPointZ', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingElementDimensions', [1 2], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingAngleMin', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingAngleMax', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingToDecklidSpoilerSpacingMax', [2 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1500', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1950', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2400', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2800', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bootLidHeight_pos1290', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bootLidHeight_pos1675', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dashHeight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelArchLinersFront', [1 1], 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelArchLinersRear', [1 1], 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bicycleModel', 1, 'slBus81_bicycleModel', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofHeight_neg625mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_neg224_1mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'roofheight_pos605mm', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_mm_0', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_mm_TBA1', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_mm_TBA2', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_deg_0', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_deg_TBA1', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rearWingDeflection_deg_TBA2', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1595', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2170', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2425', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg2740', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1397', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'bonnetHeight_neg1675', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus83_body', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'CoG', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'trackWidth', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus84_clevis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'POS1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'yOffset', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus85_upperAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'UBJ_UPRIGHT_POS_1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightConnector', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightBalljointAdjust', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJointCAD', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus88_damper', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'fittedLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxCompression', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxDroop', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassisPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus89_Pot', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'pivotPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'armPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'shaftAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus90_rocker', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ARBPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damperPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus91_lowerAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'toeRodChassis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus92_chassis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'potPickupPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus93_upright', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'rotationAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterPlaneAlongUBJ2LBJAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelCenterDelta2KPI', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelAxleOffsetToUpright', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'wheelMatingFace2RotatationalAxis', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus94_rear', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'tyreCorneringStiffness', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyrecenterPoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryInside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreGeometryOutside', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreRadius', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tyreWidth', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CentreLineLaser', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationLeft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RideHeightReferenceLocationRight', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'clevis', 1, 'slBus84_clevis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upperAArm', 1, 'slBus85_upperAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'damper', 1, 'slBus88_damper', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pot', 1, 'slBus89_Pot', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rocker', 1, 'slBus90_rocker', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lowerAArm', 1, 'slBus91_lowerAArm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'chassis', 1, 'slBus92_chassis', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'upright', 1, 'slBus93_upright', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus95_clevis', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'POS1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'POS5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'yOffset', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus97_damper', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'chassisPickup', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fittedLength', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxCompression', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxDroop', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'slBus9_upperAArm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'UBJ_UPRIGHT_POS_1', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_2', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_3', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_4', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'UBJ_UPRIGHT_POS_5', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightConnector', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'uprightBalljointAdjust', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fore', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'aft', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJoint', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ballJointCAD', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
