function cache = smp_cache_add(cache, fpath, team_index, team_acronym, ...
                               info, load_ok, err_msg, group_key)
% SMP_CACHE_ADD  Add a single file entry to the cache manifest.

    if nargin < 8 || isempty(group_key), group_key = ''; end

    d = dir(fpath);
    if isempty(d)
        file_size    = 0;
        mod_datenum  = 0;
        mod_datetime = NaT;
    else
        file_size    = d.bytes;
        mod_datenum  = d.datenum;
        mod_datetime = datetime(mod_datenum, 'ConvertFrom', 'datenum');
    end

    % Safely extract info fields with fallback to empty string
    driver       = safe_str(info, 'driver');
    car_number   = safe_str(info, 'car_number');
    team_name    = safe_str(info, 'team_name');
    vehicle      = safe_str(info, 'vehicle');
    manufacturer = safe_str(info, 'manufacturer');
    engine_id    = safe_str(info, 'engine_id');
    venue        = safe_str(info, 'venue');
    session      = safe_str(info, 'session');
    run          = safe_str(info, 'run');
    date_str     = safe_str(info, 'date');
    time_str     = safe_str(info, 'time');
    year_str     = safe_str(info, 'year');
    log_date     = safe_str(info, 'log_date');

    new_row = table( ...
        {fpath},         ...
        team_index,      ...
        {team_acronym},  ...
        file_size,       ...
        mod_datenum,     ...
        mod_datetime,    ...
        {driver},        ...
        {car_number},    ...
        {team_name},     ...
        {vehicle},       ...
        {manufacturer},  ...
        {engine_id},     ...
        {venue},         ...
        {session},       ...
        {run},           ...
        {date_str},      ...
        {time_str},      ...
        {year_str},      ...
        {log_date},      ...
        load_ok,         ...
        false,           ...
        {err_msg},       ...
        datetime('now'), ...
        {group_key},     ...
        'VariableNames', { ...
            'Path','TeamIndex','TeamAcronym', ...
            'FileSize','LastModifiedNum','LastModified', ...
            'Driver','CarNumber','TeamName', ...
            'Vehicle','Manufacturer','EngineID', ...
            'Venue','Session','Run', ...
            'Date','Time','Year','LogDate', ...
            'LoadOK','Missing','ErrorMsg','CachedAt','GroupKey'});

    cache.manifest = [cache.manifest; new_row];
end


function val = safe_str(s, field)
    if isstruct(s) && isfield(s, field) && ~isempty(s.(field))
        val = s.(field);
    else
        val = '';
    end
end
