%% smp_create_session_metadata_template.m
% Run once to create the session_metadata.xlsx template in this folder.
% Fill in one row per session with the .ld file paths and environmental data.

out_file = fullfile(fileparts(mfilename('fullpath')), 'session_metadata.xlsx');

headers = { ...
    'DASH_FILE', ...
    'ECU_FILE', ...
    'Temperature_C', ...
    'Wind_Direction_deg', ...
    'Wind_Speed_kph', ...
    'Pressure_hPa', ...
    'Humidity_pct', ...
    'Density', ...
    'Start_Mass_kg', ...
    'Finish_Mass_kg' ...
};

example = { ...
    'E:\2026\T01_QLR\Dash\20260505-156890009.ld', ...
    'E:\2026\T01_QLR\ECU\S1_#26485_20260505_125309.ld', ...
    25, 270, 15, 1013, 55, 1.184, 1350, 1280 ...
};

xlswrite(out_file, headers, 'Sheet1', 'A1');
xlswrite(out_file, example, 'Sheet1', 'A2');

fprintf('Template created: %s\n', out_file);
fprintf('Edit the example row and add one row per session.\n');
