// ============================================================
// SMP_CONFIG.JS — V8SC Pit Wall
// AUTO-GENERATED by smp_generate_config.m — do not hand-edit
// Generated: 2026-03-31 13:25:20
// ============================================================

const SMP_CONFIG = {

  TITLE:      'V8SC PIT WALL',

  // ── Azure Function endpoint ─────────────────────────────────
  // Replace YOUR_FUNCTION_APP_NAME with your actual Function App name
  // v8sc-pitwall-functions-fdawdwhbcnhmdhdy.australiaeast-01.azurewebsites.net
  FUNCTION_URL: 'https://v8sc-pitwall-functions-fdawdwhbcnhmdhdy.australiaeast-01.azurewebsites.net/api/getlapstats',

  // ── Entra ID — for MSAL browser login ──────────────────────
  // Replace with your actual values from the Azure Portal
  AUTH: {
    CLIENT_ID:  '85b3434d-215c-4bfa-ba52-2368dd2a08bf',        // App Registration client ID
    TENANT_ID:  '43f9227d-3dd6-4a9e-8ffd-2bd4a184889a',        // Directory/tenant ID
    SCOPES:     ['User.Read'],
  },

  AUTO_LOAD_EVENTS:       2,
  ROW_WARNING_THRESHOLD:  12000,

  // ── Event order (chronological) ────────────────────────────
  EVENT_ORDER: [
    'SMP', 'AGP', 'TAU', 'CCH', 'TAS', 'PER', 'DAR', 'TSV', 'QRW', 'TMB', 'BAT', 'GST', 'SAN', 'ADL',
  ],

  // ── Manufacturer colours ─────────────────────────────────────
  MFR: {
    Ford:      { bg: 'rgba(0,87,184,0.75)',   bd: '#0057B8', lt: '#4A9EFF' },
    Chevrolet: { bg: 'rgba(245,196,0,0.75)',  bd: '#F5C400', lt: '#F5C400' },
    Toyota:    { bg: 'rgba(235,10,30,0.75)',  bd: '#EB0A1E', lt: '#FF6B7A' },
    default:   { bg: 'rgba(90,102,120,0.6)',  bd: '#5A6678', lt: '#8899AA' },
  },

  // ── Chart defaults ────────────────────────────────────────────
  CHART: {
    SCALE: {
      ticks: { color: '#5A6678', font: { size: 9, family: 'JetBrains Mono' } },
      grid:  { color: 'rgba(255,255,255,0.04)' },
    },
    BASE: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: { labels: { color: '#5A6678', font: { size: 10, family: 'JetBrains Mono' }, boxWidth: 10, padding: 10 } },
        tooltip: {
          backgroundColor: 'rgba(15,19,24,0.95)',
          borderColor: 'rgba(255,255,255,0.12)',
          borderWidth: 1,
          titleColor: '#E8EDF2',
          bodyColor:  '#8899AA',
          titleFont: { family: 'JetBrains Mono', size: 11 },
          bodyFont:  { family: 'JetBrains Mono', size: 10 },
          padding: 10,
          position: 'nearest',
          xAlign: 'left',
        },
      },
    },
    POINT_RADIUS:       2.5,
    POINT_RADIUS_SMALL: 0.5,
    POINT_HOVER:        4,
  },

  // ── X axis options ─────────────────────────────────────────
  X_AXIS_OPTIONS: [
    { value: 'lap_number', label: 'Lap Number' },
    { value: 'lap_time',   label: 'Lap Time (s)' },
    { value: '------',     label: '------', disabled: true },
  ],

  // ── Hardcoded tabs ─────────────────────────────────────────
  HARDCODED_TABS: [
    { id: 'overview',  label: 'OVERVIEW'  },
    { id: 'channels',  label: 'CHANNELS'  },
    { id: 'timing',    label: 'TIMING'    },
  ],

  // ── Excel-driven tabs (auto-generated) ────────────────────
  EXCEL_TABS: [
    { id: 'engine', label: 'ENGINE', subtabs: [
      { id: 'engine', label: 'ENGINE', plots: [
        { title: 'Engine RPM',          field: 'engine_speed_max',               plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Oil Temperature',     field: 'engine_oil_temperature_mean',    plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Oil Pressure',        field: 'engine_oil_pressure_mean',       plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Coolant Temperature', field: 'coolant_temperature_mean',       plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Coolant Pressure',    field: 'coolant_pressure_mean',          plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Crankcase Pressure',  field: 'engine_crankcase_pressure_mean', plotType: 'scatter', xField: 'lap_number', yLim: null },
      ] },
    ] },
    { id: 'performance', label: 'PERFORMANCE', subtabs: [
      { id: 'tyre-e', label: 'TYRE_E', plots: [
        { title: 'Top Speed',             field: 'ground_speed_max',          plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Throttle Position',     field: 'throttle_position_mean',    plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Brake Pressure Front',  field: 'brake_pressure_front_max',  plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Brake Pressure Rear',   field: 'brake_pressure_rear_max',   plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Gear',                  field: 'gear_mean',                 plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Steering Angle',        field: 'steering_angle_max',        plotType: 'scatter', xField: 'lap_number', yLim: null },
      ] },
    ] },
    { id: 'systems', label: 'SYSTEMS', subtabs: [
      { id: 'systems', label: 'SYSTEMS', plots: [
        { title: 'PDM Total Current',  field: 'pdm_total_current_mean',          plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'CAN 1 Utilisation',  field: 'can_1_bus_utilization_mean',      plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'ECU CPU Usage',      field: 'ecu_cpu_usage_mean',              plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Fuel Pressure',      field: 'fuel_pressure_mean',              plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Transmission Temp',  field: 'transmission_temperature_mean',   plotType: 'scatter', xField: 'lap_number', yLim: null },
        { title: 'Fuel Used',          field: 'fuel_used_max',                   plotType: 'scatter', xField: 'lap_number', yLim: null },
      ] },
    ] },
  ],

  // ── All numeric channel fields (for dropdowns) ────────────
  ALL_CHANNELS: [
    'lap_number','lap_time',
    'ground_speed_max','ground_speed_min','ground_speed_mean','ground_speed_mean_nz',
    'engine_speed_max','engine_speed_min','engine_speed_mean','engine_speed_mean_nz',
    'throttle_position_max','throttle_position_min','throttle_position_mean','throttle_position_mean_nz',
    'throttle_pedal_max','throttle_pedal_min','throttle_pedal_mean','throttle_pedal_mean_nz',
    'brake_pressure_front_max','brake_pressure_front_min','brake_pressure_front_mean','brake_pressure_front_mean_nz',
    'brake_pressure_rear_max','brake_pressure_rear_min','brake_pressure_rear_mean','brake_pressure_rear_mean_nz',
    'gear_max','gear_min','gear_mean','gear_mean_nz',
    'gear_ratio_max','gear_ratio_min','gear_ratio_mean','gear_ratio_mean_nz',
    'steering_angle_max','steering_angle_min','steering_angle_mean','steering_angle_mean_nz',
    'engine_oil_temperature_max','engine_oil_temperature_min','engine_oil_temperature_mean','engine_oil_temperature_mean_nz',
    'engine_oil_pressure_max','engine_oil_pressure_min','engine_oil_pressure_mean','engine_oil_pressure_mean_nz',
    'coolant_temperature_max','coolant_temperature_min','coolant_temperature_mean','coolant_temperature_mean_nz',
    'coolant_pressure_max','coolant_pressure_min','coolant_pressure_mean','coolant_pressure_mean_nz',
    'engine_crankcase_pressure_max','engine_crankcase_pressure_min','engine_crankcase_pressure_mean','engine_crankcase_pressure_mean_nz',
    'fuel_temperature_max','fuel_temperature_min','fuel_temperature_mean','fuel_temperature_mean_nz',
    'fuel_pressure_max','fuel_pressure_min','fuel_pressure_mean','fuel_pressure_mean_nz',
    'fuel_used_max','fuel_used_min','fuel_used_mean','fuel_used_mean_nz',
    'fuel_closed_loop_diagnostic_max','fuel_closed_loop_diagnostic_min','fuel_closed_loop_diagnostic_mean','fuel_closed_loop_diagnostic_mean_nz',
    'inlet_manifold_pressure_max','inlet_manifold_pressure_min','inlet_manifold_pressure_mean','inlet_manifold_pressure_mean_nz',
    'inlet_manifold_pressure_est_max','inlet_manifold_pressure_est_min','inlet_manifold_pressure_est_mean','inlet_manifold_pressure_est_mean_nz',
    'inlet_air_temperature_max','inlet_air_temperature_min','inlet_air_temperature_mean','inlet_air_temperature_mean_nz',
    'transmission_temperature_max','transmission_temperature_min','transmission_temperature_mean','transmission_temperature_mean_nz',
    'transmission_pressure_max','transmission_pressure_min','transmission_pressure_mean','transmission_pressure_mean_nz',
    'pdm_total_current_max','pdm_total_current_min','pdm_total_current_mean','pdm_total_current_mean_nz',
    'pdm2_total_current_max','pdm2_total_current_min','pdm2_total_current_mean','pdm2_total_current_mean_nz',
    'can_1_bus_utilization_max','can_1_bus_utilization_min','can_1_bus_utilization_mean',
    'can_2_bus_utilization_max','can_2_bus_utilization_min','can_2_bus_utilization_mean',
    'can_3_bus_utilization_max','can_3_bus_utilization_min','can_3_bus_utilization_mean',
    'ecu_cpu_usage_max','ecu_cpu_usage_min','ecu_cpu_usage_mean','ecu_cpu_usage_mean_nz',
    'cpu_usage_max','cpu_usage_min','cpu_usage_mean','cpu_usage_mean_nz',
    'c1_damper_pos_fl_max','c1_damper_pos_fl_min','c1_damper_pos_fl_mean',
    'c1_damper_pos_fr_max','c1_damper_pos_fr_min','c1_damper_pos_fr_mean',
    'c1_damper_pos_rl_max','c1_damper_pos_rl_min','c1_damper_pos_rl_mean',
    'c1_damper_pos_rr_max','c1_damper_pos_rr_min','c1_damper_pos_rr_mean',
    'c1_susp_pos_fl_max','c1_susp_pos_fl_min','c1_susp_pos_fl_mean',
    'c1_susp_pos_fr_max','c1_susp_pos_fr_min','c1_susp_pos_fr_mean',
    'c1_susp_pos_rl_max','c1_susp_pos_rl_min','c1_susp_pos_rl_mean',
    'c1_susp_pos_rr_max','c1_susp_pos_rr_min','c1_susp_pos_rr_mean',
    'c1_cockpit_temp_max','c1_cockpit_temp_min','c1_cockpit_temp_mean',
    'c1_driver_suit_temp_max','c1_driver_suit_temp_min','c1_driver_suit_temp_mean',
    'c1_driver_helmet_temp_max','c1_driver_helmet_temp_min','c1_driver_helmet_temp_mean',
    'c1_power_steering_pressure_max','c1_power_steering_pressure_min','c1_power_steering_pressure_mean',
    'wheel_speed_front_left_max','wheel_speed_front_left_min','wheel_speed_front_left_mean',
    'wheel_speed_front_right_max','wheel_speed_front_right_min','wheel_speed_front_right_mean',
    'wheel_speed_rear_left_max','wheel_speed_rear_left_min','wheel_speed_rear_left_mean',
    'wheel_speed_rear_right_max','wheel_speed_rear_right_min','wheel_speed_rear_right_mean',
    'tpm1s_fl_ws_temp_max','tpm1s_fl_ws_temp_mean','tpm1s_fl_ws_press_max','tpm1s_fl_ws_press_mean',
    'tpm1s_fr_ws_temp_max','tpm1s_fr_ws_temp_mean','tpm1s_fr_ws_press_max','tpm1s_fr_ws_press_mean',
    'tpm1s_rl_ws_temp_max','tpm1s_rl_ws_temp_mean','tpm1s_rl_ws_press_max','tpm1s_rl_ws_press_mean',
    'tpm1s_rr_ws_temp_max','tpm1s_rr_ws_temp_mean','tpm1s_rr_ws_press_max','tpm1s_rr_ws_press_mean',
    'adr_acceleration_x_max','adr_acceleration_x_min','adr_acceleration_x_mean',
    'adr_acceleration_y_max','adr_acceleration_y_min','adr_acceleration_y_mean',
    'adr_acceleration_z_max','adr_acceleration_z_min','adr_acceleration_z_mean',
    'acceleration_x_filt_max','acceleration_x_filt_min','acceleration_x_filt_mean',
    'acceleration_y_filt_max','acceleration_y_filt_min','acceleration_y_filt_mean',
    'acceleration_z_filt_max','acceleration_z_filt_min','acceleration_z_filt_mean',
    'gps_speed_max','gps_speed_mean','gps_altitude_max','gps_altitude_mean',
    'laps_since_pit_max','laps_since_pit_mean',
    'lap_distance_max','lap_distance_mean',
    'vcs_pit_entry_speed_max','vcs_pit_exit_speed_max',
    'brakinggatevch_max','brakinggatevch_mean',
    'entrygatevch_max','entrygatevch_mean',
    'midcrngatevch_max','midcrngatevch_mean',
    'exitgatevch_max','exitgatevch_mean',
    'straightgatevch_max','straightgatevch_mean',
    'brakebiasvch_max','brakebiasvch_mean',
    'rl_slipvch_max','rl_slipvch_mean',
    'avgcrnvch_max','avgcrnvch_mean',
    'fl_locktimervch_max','fl_locktimervch_mean',
    'fr_locktimervch_max','fr_locktimervch_mean',
    'rl_locktimervch_max','rl_locktimervch_mean',
  ],

};
