%% SMP_GENERATE_CONFIG
% Reads V8SC_PitWall_plot_organizer.xlsx and generates smp_config.js
% for the V8SC Pit Wall dashboard.
%
% ── HOW TO USE ────────────────────────────────────────────────
% 1. Fill in your plots in the Excel file (see column guide below)
% 2. Set EXCEL_PATH and OUTPUT_PATH below
% 3. Run this script
% 4. Copy smp_config.js to C:\PocketBase\pb_public\
% 5. Hard refresh the dashboard (Ctrl+Shift+R)
%
% ── EXCEL COLUMN GUIDE ────────────────────────────────────────
% plotName      Display name shown on the chart card title
% plotType      Chart type: scatter | bar | line | histogram
% mathFunction  Operation: max | min | mean | mean_nz
%               Combined with yAxis1 to form the PocketBase field name
%               e.g. yAxis1=ground_speed + mathFunction=max -> ground_speed_max
% xAxis         X axis field: lap_number | lap_time (or any channel base name)
% yAxis1        Base channel name (without math suffix)
%               Must match PocketBase field name minus the _max/_min/_mean suffix
% colours       Always: manufacturer
% Tab           Tab name e.g. Engine | Performance | Systems
%               Overview, Channels, Timing are hardcoded - don't add rows for these
% SubTab        Sub-tab name e.g. Engine | Tyre E | Tyre S | Aero | Deg | Timing
% yLim          Optional y-axis limits as [min, max] e.g. [0, 300]
%               Leave blank for auto
%
% ── TABS THAT ARE HARDCODED (do NOT add rows for these) ───────
%   Overview  - stat strip, falling speed, custom scatter A & B
%   Channels  - channel browser + custom channels sub-tab
%   Timing    - blank placeholder
% =========================================================

%% ── CONFIG ────────────────────────────────────────────────────

EXCEL_PATH  = 'C:\SimEnv\dataAcquisition\serverInteraction\V8SC_PitWall_plot_organizer.xlsx';
OUTPUT_PATH = 'C:\PocketBase\pb_public\smp_config.js';

% ── Event order (chronological — edit each season) ────────────
EVENT_ORDER = { ...
    'SMP',...
    'AGP',...
    'TAU',...
    'CCH',...
    'TAS',...
    'PER',...
    'DAR',...
    'TSV',...
    'QRW',...
    'TMB',...
    'BAT',...
    'GST',...
    'SAN',...
    'ADL'
    };

% ── Number of most recent events to auto-load on startup ──────
AUTO_LOAD_EVENTS = 2;

% ── Row warning threshold ─────────────────────────────────────
ROW_WARNING_THRESHOLD = 12000;

% ── PIN ───────────────────────────────────────────────────────
PIN = '7896';

%% ── READ EXCEL ────────────────────────────────────────────────

fprintf('Reading Excel: %s\n', EXCEL_PATH);
T = readtable(EXCEL_PATH, 'Sheet', 'plotting');

% Normalise column names (trim whitespace)
T.Properties.VariableNames = strtrim(T.Properties.VariableNames);

% Required columns
req_cols = {'plotName','plotType','mathFunction','xAxis','yAxis1','Tab','SubTab'};
for c = req_cols
    if ~ismember(c{1}, T.Properties.VariableNames)
        error('Missing required column: %s', c{1});
    end
end

% Remove rows where Tab is empty
valid = ~cellfun(@(x) isempty(x) || (ischar(x) && all(isspace(x))), ...
    cellstr(string(T.Tab)));
T = T(valid, :);

fprintf('Found %d valid plot rows.\n', height(T));

%% ── BUILD TAB/SUBTAB STRUCTURE ───────────────────────────────

% Get unique tabs preserving order of first appearance
tabs     = unique(string(T.Tab),    'stable');
subtabs  = unique(string(T.SubTab), 'stable');

% Build nested structure: tab -> {subtab -> [plots]}
% Use to_matlab_id (underscores) for struct field names
% Use to_js_id (hyphens) for JS output strings
tab_struct = struct();
for ti = 1:numel(tabs)
    tab    = tabs(ti);
    mat_id = to_matlab_id(tab);   % used as MATLAB struct key
    tab_rows = T(string(T.Tab) == tab, :);
    sub_list = unique(string(tab_rows.SubTab), 'stable');
    tab_struct.(mat_id).label    = tab;
    tab_struct.(mat_id).js_id    = to_js_id(tab);   % stored for JS output
    tab_struct.(mat_id).subtabs  = struct();
    for si = 1:numel(sub_list)
        sub     = sub_list(si);
        sub_mid = to_matlab_id(sub);   % MATLAB struct key
        sub_rows = tab_rows(string(tab_rows.SubTab) == sub, :);
        plots = build_plots(sub_rows);
        tab_struct.(mat_id).subtabs.(sub_mid).label  = sub;
        tab_struct.(mat_id).subtabs.(sub_mid).js_id  = to_js_id(sub);
        tab_struct.(mat_id).subtabs.(sub_mid).plots  = plots;
    end
end

%% ── WRITE smp_config.js ───────────────────────────────────────

fprintf('Writing: %s\n', OUTPUT_PATH);
fid = fopen(OUTPUT_PATH, 'w', 'n', 'UTF-8');
if fid < 0
    error('Cannot open output file: %s', OUTPUT_PATH);
end

w = @(s) fprintf(fid, '%s\n', s);

w('// ============================================================');
w('// SMP_CONFIG.JS — V8SC Pit Wall');
w('// AUTO-GENERATED by smp_generate_config.m — do not hand-edit');
w(sprintf('// Generated: %s', datestr(now, 'yyyy-mm-dd HH:MM:SS')));
w('// ============================================================');
w('');
w('const SMP_CONFIG = {');
w('');

% ── Branding / PIN / PocketBase ───────────────────────────────
w('  TITLE:      ''V8SC PIT WALL'',');
w(sprintf('  PIN:        ''%s'',', PIN));
w('  PB_URL:     window.location.origin,');
w('  COLLECTION: ''lap_stats'',');
w(sprintf('  AUTO_LOAD_EVENTS:       %d,', AUTO_LOAD_EVENTS));
w(sprintf('  ROW_WARNING_THRESHOLD:  %d,', ROW_WARNING_THRESHOLD));
w('');

% ── Event order ───────────────────────────────────────────────
w('  // ── Event order (chronological) ───────────────────────');
w('  EVENT_ORDER: [');
event_strs = strjoin(cellfun(@(e) sprintf('''%s''', e), EVENT_ORDER, 'UniformOutput', false), ', ');
w(sprintf('    %s,', event_strs));
w('  ],');
w('');

% ── Manufacturer colours ──────────────────────────────────────
w('  // ── Manufacturer colours ────────────────────────────────');
w('  MFR: {');
w('    Ford:      { bg: ''rgba(0,87,184,0.75)'',   bd: ''#0057B8'', lt: ''#4A9EFF'' },');
w('    Chevrolet: { bg: ''rgba(245,196,0,0.75)'',  bd: ''#F5C400'', lt: ''#F5C400'' },');
w('    Toyota:    { bg: ''rgba(235,10,30,0.75)'',  bd: ''#EB0A1E'', lt: ''#FF6B7A'' },');
w('    default:   { bg: ''rgba(90,102,120,0.6)'',  bd: ''#5A6678'', lt: ''#8899AA'' },');
w('  },');
w('');

% ── Chart defaults ────────────────────────────────────────────
w('  // ── Chart defaults ──────────────────────────────────────');
w('  CHART: {');
w('    SCALE: {');
w('      ticks: { color: ''#5A6678'', font: { size: 9, family: ''JetBrains Mono'' } },');
w('      grid:  { color: ''rgba(255,255,255,0.04)'' },');
w('    },');
w('    BASE: {');
w('      responsive: true,');
w('      maintainAspectRatio: false,');
w('      plugins: {');
w('        legend: { labels: { color: ''#5A6678'', font: { size: 10, family: ''JetBrains Mono'' }, boxWidth: 10, padding: 10 } },');
w('        tooltip: {');
w('          backgroundColor: ''rgba(15,19,24,0.95)'',');
w('          borderColor: ''rgba(255,255,255,0.12)'',');
w('          borderWidth: 1,');
w('          titleColor: ''#E8EDF2'',');
w('          bodyColor:  ''#8899AA'',');
w('          titleFont: { family: ''JetBrains Mono'', size: 11 },');
w('          bodyFont:  { family: ''JetBrains Mono'', size: 10 },');
w('          padding: 10,');
w('          position: ''nearest'',');
w('          xAlign: ''left'',');
w('        },');
w('      },');
w('    },');
w('    POINT_RADIUS:       2.5,');
w('    POINT_RADIUS_SMALL: 0.5,');
w('    POINT_HOVER:        4,');
w('  },');
w('');

% ── X axis options ────────────────────────────────────────────
w('  // ── X axis options (lap_number and lap_time always first) ─');
w('  X_AXIS_OPTIONS: [');
w('    { value: ''lap_number'', label: ''Lap Number'' },');
w('    { value: ''lap_time'',   label: ''Lap Time (s)'' },');
w('    { value: ''------'',     label: ''------'',    disabled: true },');
w('  ],');
w('');

% ── Hardcoded tabs (Overview, Channels, Timing) ───────────────
w('  // ── Hardcoded tabs ──────────────────────────────────────');
w('  HARDCODED_TABS: [');
w('    { id: ''overview'',  label: ''OVERVIEW''  },');
w('    { id: ''channels'',  label: ''CHANNELS''  },');
w('    { id: ''timing'',    label: ''TIMING''    },');
w('  ],');
w('');

% ── Excel-driven tabs ─────────────────────────────────────────
w('  // ── Excel-driven tabs (auto-generated) ─────────────────');
w('  EXCEL_TABS: [');
tab_ids = fieldnames(tab_struct);
for ti = 1:numel(tab_ids)
    tid = tab_ids{ti};
    tab = tab_struct.(tid);
    w(sprintf('    { id: ''%s'', label: ''%s'', subtabs: [', tab.js_id, upper(char(tab.label))));
    sub_ids = fieldnames(tab.subtabs);
    for si = 1:numel(sub_ids)
        sid = sub_ids{si};
        sub = tab.subtabs.(sid);
        w(sprintf('      { id: ''%s'', label: ''%s'', plots: [', sub.js_id, upper(char(sub.label))));
        for pi = 1:numel(sub.plots)
            p = sub.plots{pi};
            ylim_str = 'null';
            if ~isempty(p.yLim)
                ylim_str = sprintf('[%s]', p.yLim);
            end
            w(sprintf('        { title: ''%s'', field: ''%s'', plotType: ''%s'', xField: ''%s'', yLim: %s },', ...
                p.title, p.field, p.plotType, p.xField, ylim_str));
        end
        w('      ] },');
    end
    w('    ] },');
end
w('  ],');
w('');

% ── All channels (for dropdowns) ─────────────────────────────
w('  // ── All numeric channel fields (for dropdowns) ─────────');
w('  ALL_CHANNELS: [');
all_ch = get_all_channels();
for ci = 1:numel(all_ch)
    w(sprintf('    ''%s'',', all_ch{ci}));
end
w('  ],');
w('');
w('};');

fclose(fid);
fprintf('\nDone. Copy %s to C:\\PocketBase\\pb_public\\\n', OUTPUT_PATH);


% ======================================================================= %
%  HELPERS
% ======================================================================= %

function id = to_js_id(str)
% Convert a display name to a valid JS/CSS id (lowercase, hyphens)
    id = lower(strtrim(char(str)));
    id = regexprep(id, '[^a-z0-9]+', '-');
    id = regexprep(id, '^-|-$', '');
end

function id = to_matlab_id(str)
% Convert a display name to a valid MATLAB struct field name (lowercase, underscores only)
    id = lower(strtrim(char(str)));
    id = regexprep(id, '[^a-z0-9]+', '_');
    id = regexprep(id, '^_|_$', '');
    if ~isempty(id) && id(1) >= '0' && id(1) <= '9'
        id = ['f_' id];
    end
end

function plots = build_plots(rows)
% Build plot config structs from table rows
    plots = {};
    for i = 1:height(rows)
        p = struct();
        p.title    = strtrim(char(rows.plotName{i}));
        p.plotType = strtrim(lower(char(rows.plotType{i})));
        math_fn    = strtrim(lower(char(rows.mathFunction{i})));
        base_ch    = strtrim(lower(char(rows.yAxis1{i})));
        % Replace spaces with underscores in channel name
        base_ch    = regexprep(base_ch, '\s+', '_');
        p.field    = [base_ch '_' math_fn];
        % X field
        xax = strtrim(lower(char(rows.xAxis{i})));
        xax = regexprep(xax, '\s+', '_');
        p.xField   = xax;
        % Y limits
        p.yLim = '';
        if ismember('yLim', rows.Properties.VariableNames)
            yl = rows.yLim(i);
            if ~isempty(yl) && ~(isnumeric(yl) && isnan(yl))
                p.yLim = strtrim(char(string(yl)));
                % Strip brackets if present, reformat
                p.yLim = regexprep(p.yLim, '[\[\]]', '');
            end
        end
        plots{end+1} = p; %#ok<AGROW>
    end
end

function s = plots_to_js(plots, indent)
    s = '';
    for i = 1:numel(plots)
        % unused — inline writing used instead
    end
end

function channels = get_all_channels()
% Return the full list of known PocketBase numeric channel fields
    channels = { ...
        'lap_number','lap_time', ...
        'ground_speed_max','ground_speed_min','ground_speed_mean','ground_speed_mean_nz', ...
        'engine_speed_max','engine_speed_min','engine_speed_mean','engine_speed_mean_nz', ...
        'throttle_position_max','throttle_position_min','throttle_position_mean','throttle_position_mean_nz', ...
        'throttle_pedal_max','throttle_pedal_min','throttle_pedal_mean','throttle_pedal_mean_nz', ...
        'brake_pressure_front_max','brake_pressure_front_min','brake_pressure_front_mean','brake_pressure_front_mean_nz', ...
        'brake_pressure_rear_max','brake_pressure_rear_min','brake_pressure_rear_mean','brake_pressure_rear_mean_nz', ...
        'gear_max','gear_min','gear_mean','gear_mean_nz', ...
        'gear_ratio_max','gear_ratio_min','gear_ratio_mean','gear_ratio_mean_nz', ...
        'steering_angle_max','steering_angle_min','steering_angle_mean','steering_angle_mean_nz', ...
        'engine_oil_temperature_max','engine_oil_temperature_min','engine_oil_temperature_mean','engine_oil_temperature_mean_nz', ...
        'engine_oil_pressure_max','engine_oil_pressure_min','engine_oil_pressure_mean','engine_oil_pressure_mean_nz', ...
        'coolant_temperature_max','coolant_temperature_min','coolant_temperature_mean','coolant_temperature_mean_nz', ...
        'coolant_pressure_max','coolant_pressure_min','coolant_pressure_mean','coolant_pressure_mean_nz', ...
        'engine_crankcase_pressure_max','engine_crankcase_pressure_min','engine_crankcase_pressure_mean','engine_crankcase_pressure_mean_nz', ...
        'fuel_temperature_max','fuel_temperature_min','fuel_temperature_mean','fuel_temperature_mean_nz', ...
        'fuel_pressure_max','fuel_pressure_min','fuel_pressure_mean','fuel_pressure_mean_nz', ...
        'fuel_used_max','fuel_used_min','fuel_used_mean','fuel_used_mean_nz', ...
        'fuel_closed_loop_diagnostic_max','fuel_closed_loop_diagnostic_min','fuel_closed_loop_diagnostic_mean','fuel_closed_loop_diagnostic_mean_nz', ...
        'inlet_manifold_pressure_max','inlet_manifold_pressure_min','inlet_manifold_pressure_mean','inlet_manifold_pressure_mean_nz', ...
        'inlet_manifold_pressure_est_max','inlet_manifold_pressure_est_min','inlet_manifold_pressure_est_mean','inlet_manifold_pressure_est_mean_nz', ...
        'inlet_air_temperature_max','inlet_air_temperature_min','inlet_air_temperature_mean','inlet_air_temperature_mean_nz', ...
        'transmission_temperature_max','transmission_temperature_min','transmission_temperature_mean','transmission_temperature_mean_nz', ...
        'transmission_pressure_max','transmission_pressure_min','transmission_pressure_mean','transmission_pressure_mean_nz', ...
        'pdm_total_current_max','pdm_total_current_min','pdm_total_current_mean','pdm_total_current_mean_nz', ...
        'pdm2_total_current_max','pdm2_total_current_min','pdm2_total_current_mean','pdm2_total_current_mean_nz', ...
        'pdm2_output_1_current_fp_main_max','pdm2_output_1_current_fp_main_mean', ...
        'pdm2_output_15_current_lp_1_max','pdm2_output_15_current_lp_1_mean', ...
        'pdm2_output_16_current_lp_2_max','pdm2_output_16_current_lp_2_mean', ...
        'pdm2_output_17_current_lp_3_max','pdm2_output_17_current_lp_3_mean', ...
        'pdm2_output_18_current_lp_4_max','pdm2_output_18_current_lp_4_mean', ...
        'can_1_bus_utilization_max','can_1_bus_utilization_min','can_1_bus_utilization_mean', ...
        'can_2_bus_utilization_max','can_2_bus_utilization_min','can_2_bus_utilization_mean', ...
        'can_3_bus_utilization_max','can_3_bus_utilization_min','can_3_bus_utilization_mean', ...
        'ecu_cpu_usage_max','ecu_cpu_usage_min','ecu_cpu_usage_mean','ecu_cpu_usage_mean_nz', ...
        'cpu_usage_max','cpu_usage_min','cpu_usage_mean','cpu_usage_mean_nz', ...
        'c1_damper_pos_fl_max','c1_damper_pos_fl_min','c1_damper_pos_fl_mean', ...
        'c1_damper_pos_fr_max','c1_damper_pos_fr_min','c1_damper_pos_fr_mean', ...
        'c1_damper_pos_rl_max','c1_damper_pos_rl_min','c1_damper_pos_rl_mean', ...
        'c1_damper_pos_rr_max','c1_damper_pos_rr_min','c1_damper_pos_rr_mean', ...
        'c1_damper_volts_fl_max','c1_damper_volts_fl_min','c1_damper_volts_fl_mean', ...
        'c1_damper_volts_fr_max','c1_damper_volts_fr_min','c1_damper_volts_fr_mean', ...
        'c1_damper_volts_rl_max','c1_damper_volts_rl_min','c1_damper_volts_rl_mean', ...
        'c1_damper_volts_rr_max','c1_damper_volts_rr_min','c1_damper_volts_rr_mean', ...
        'c1_susp_pos_fl_max','c1_susp_pos_fl_min','c1_susp_pos_fl_mean', ...
        'c1_susp_pos_fr_max','c1_susp_pos_fr_min','c1_susp_pos_fr_mean', ...
        'c1_susp_pos_rl_max','c1_susp_pos_rl_min','c1_susp_pos_rl_mean', ...
        'c1_susp_pos_rr_max','c1_susp_pos_rr_min','c1_susp_pos_rr_mean', ...
        'c1_cockpit_temp_max','c1_cockpit_temp_min','c1_cockpit_temp_mean', ...
        'c1_driver_suit_temp_max','c1_driver_suit_temp_min','c1_driver_suit_temp_mean', ...
        'c1_driver_helmet_temp_max','c1_driver_helmet_temp_min','c1_driver_helmet_temp_mean', ...
        'c1_power_steering_pressure_max','c1_power_steering_pressure_min','c1_power_steering_pressure_mean', ...
        'wheel_speed_front_left_max','wheel_speed_front_left_min','wheel_speed_front_left_mean', ...
        'wheel_speed_front_right_max','wheel_speed_front_right_min','wheel_speed_front_right_mean', ...
        'wheel_speed_rear_left_max','wheel_speed_rear_left_min','wheel_speed_rear_left_mean', ...
        'wheel_speed_rear_right_max','wheel_speed_rear_right_min','wheel_speed_rear_right_mean', ...
        'tpm1s_fl_ws_temp_max','tpm1s_fl_ws_temp_mean','tpm1s_fl_ws_press_max','tpm1s_fl_ws_press_mean', ...
        'tpm1s_fr_ws_temp_max','tpm1s_fr_ws_temp_mean','tpm1s_fr_ws_press_max','tpm1s_fr_ws_press_mean', ...
        'tpm1s_rl_ws_temp_max','tpm1s_rl_ws_temp_mean','tpm1s_rl_ws_press_max','tpm1s_rl_ws_press_mean', ...
        'tpm1s_rr_ws_temp_max','tpm1s_rr_ws_temp_mean','tpm1s_rr_ws_press_max','tpm1s_rr_ws_press_mean', ...
        'adr_acceleration_x_max','adr_acceleration_x_min','adr_acceleration_x_mean', ...
        'adr_acceleration_y_max','adr_acceleration_y_min','adr_acceleration_y_mean', ...
        'adr_acceleration_z_max','adr_acceleration_z_min','adr_acceleration_z_mean', ...
        'acceleration_x_filt_max','acceleration_x_filt_min','acceleration_x_filt_mean', ...
        'acceleration_y_filt_max','acceleration_y_filt_min','acceleration_y_filt_mean', ...
        'acceleration_z_filt_max','acceleration_z_filt_min','acceleration_z_filt_mean', ...
        'gps_speed_max','gps_speed_mean','gps_altitude_max','gps_altitude_mean', ...
        'laps_since_pit_max','laps_since_pit_mean', ...
        'lap_distance_max','lap_distance_mean', ...
        'vcs_pit_entry_speed_max','vcs_pit_exit_speed_max', ...
        'brakinggatevch_max','brakinggatevch_mean', ...
        'entrygatevch_max','entrygatevch_mean', ...
        'midcrngatevch_max','midcrngatevch_mean', ...
        'exitgatevch_max','exitgatevch_mean', ...
        'straightgatevch_max','straightgatevch_mean', ...
        'brakebiasvch_max','brakebiasvch_mean', ...
        'rl_slipvch_max','rl_slipvch_mean', ...
        'avgcrnvch_max','avgcrnvch_mean', ...
        'fl_locktimervch_max','fl_locktimervch_mean', ...
        'fr_locktimervch_max','fr_locktimervch_mean', ...
        'rl_locktimervch_max','rl_locktimervch_mean', ...
    };
end