% CREATE LAP_STATS COLLECTION IN POCKETBASE WITH ALL FIELDS
% Run this once to set up the collection schema

import matlab.net.http.*
import matlab.net.http.io.*

% ── Auth token — re-run the auth block if this has expired ──
token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJwYmNfMzE0MjYzNTgyMyIsImV4cCI6MTc3NDY3NDkzNSwiaWQiOiJjOHR1Zmc1YjF5c2ZjbGYiLCJyZWZyZXNoYWJsZSI6dHJ1ZSwidHlwZSI6ImF1dGgifQ.6DK36ZxwMC7robmy-tjT3u1rm5idHjgMGEPXZQZo8Nc';

% ── Text fields ──────────────────────────────────────────────
txt_names = {'event','venue','session','year','team','team_name','driver', ...
             'car_number','manufacturer','vehicle','group_key','source_file'};

% ── Numeric channel fields ───────────────────────────────────
num_names = { ...
    'lap_number','lap_time', ...
    'ecu_cpu_usage_max','ecu_cpu_usage_min','ecu_cpu_usage_mean','ecu_cpu_usage_mean_nz', ...
    'ground_speed_max','ground_speed_min','ground_speed_mean','ground_speed_mean_nz', ...
    'gear_max','gear_min','gear_mean','gear_mean_nz', ...
    'lap_distance_max','lap_distance_min','lap_distance_mean','lap_distance_mean_nz', ...
    'c1_damper_pos_fl_max','c1_damper_pos_fl_min','c1_damper_pos_fl_mean','c1_damper_pos_fl_mean_nz', ...
    'c1_damper_pos_fr_max','c1_damper_pos_fr_min','c1_damper_pos_fr_mean','c1_damper_pos_fr_mean_nz', ...
    'c1_damper_pos_rl_max','c1_damper_pos_rl_min','c1_damper_pos_rl_mean','c1_damper_pos_rl_mean_nz', ...
    'c1_damper_pos_rr_max','c1_damper_pos_rr_min','c1_damper_pos_rr_mean','c1_damper_pos_rr_mean_nz', ...
    'c1_cockpit_temp_max','c1_cockpit_temp_min','c1_cockpit_temp_mean','c1_cockpit_temp_mean_nz', ...
    'c1_driver_suit_temp_max','c1_driver_suit_temp_min','c1_driver_suit_temp_mean','c1_driver_suit_temp_mean_nz', ...
    'lap_time_max','lap_time_min','lap_time_mean','lap_time_mean_nz', ...
    'steering_angle_max','steering_angle_min','steering_angle_mean','steering_angle_mean_nz', ...
    'lap_number_max','lap_number_min','lap_number_mean','lap_number_mean_nz', ...
    'fuel_used_max','fuel_used_min','fuel_used_mean','fuel_used_mean_nz', ...
    'running_lap_time_max','running_lap_time_min','running_lap_time_mean','running_lap_time_mean_nz', ...
    'trip_distance_max','trip_distance_min','trip_distance_mean','trip_distance_mean_nz', ...
    'odometer_max','odometer_min','odometer_mean','odometer_mean_nz', ...
    'cpu_usage_max','cpu_usage_min','cpu_usage_mean','cpu_usage_mean_nz', ...
    'pdm_total_current_max','pdm_total_current_min','pdm_total_current_mean','pdm_total_current_mean_nz', ...
    'pdm2_output_1_current_fp_main_max','pdm2_output_1_current_fp_main_min','pdm2_output_1_current_fp_main_mean','pdm2_output_1_current_fp_main_mean_nz', ...
    'pdm2_output_15_current_lp_1_max','pdm2_output_15_current_lp_1_min','pdm2_output_15_current_lp_1_mean','pdm2_output_15_current_lp_1_mean_nz', ...
    'pdm2_output_16_current_lp_2_max','pdm2_output_16_current_lp_2_min','pdm2_output_16_current_lp_2_mean','pdm2_output_16_current_lp_2_mean_nz', ...
    'pdm2_output_17_current_lp_3_max','pdm2_output_17_current_lp_3_min','pdm2_output_17_current_lp_3_mean','pdm2_output_17_current_lp_3_mean_nz', ...
    'pdm2_output_18_current_lp_4_max','pdm2_output_18_current_lp_4_min','pdm2_output_18_current_lp_4_mean','pdm2_output_18_current_lp_4_mean_nz', ...
    'pdm2_total_current_max','pdm2_total_current_min','pdm2_total_current_mean','pdm2_total_current_mean_nz', ...
    'can_1_bus_utilization_max','can_1_bus_utilization_min','can_1_bus_utilization_mean','can_1_bus_utilization_mean_nz', ...
    'can_2_bus_utilization_max','can_2_bus_utilization_min','can_2_bus_utilization_mean','can_2_bus_utilization_mean_nz', ...
    'can_3_bus_utilization_max','can_3_bus_utilization_min','can_3_bus_utilization_mean','can_3_bus_utilization_mean_nz', ...
    'inlet_manifold_pressure_max','inlet_manifold_pressure_min','inlet_manifold_pressure_mean','inlet_manifold_pressure_mean_nz', ...
    'inlet_air_temperature_max','inlet_air_temperature_min','inlet_air_temperature_mean','inlet_air_temperature_mean_nz', ...
    'transmission_temperature_max','transmission_temperature_min','transmission_temperature_mean','transmission_temperature_mean_nz', ...
    'gear_ratio_max','gear_ratio_min','gear_ratio_mean','gear_ratio_mean_nz', ...
    'c1_driver_helmet_temp_max','c1_driver_helmet_temp_min','c1_driver_helmet_temp_mean','c1_driver_helmet_temp_mean_nz', ...
    'engine_speed_max','engine_speed_min','engine_speed_mean','engine_speed_mean_nz', ...
    'throttle_pedal_max','throttle_pedal_min','throttle_pedal_mean','throttle_pedal_mean_nz', ...
    'throttle_position_max','throttle_position_min','throttle_position_mean','throttle_position_mean_nz', ...
    'engine_oil_pressure_max','engine_oil_pressure_min','engine_oil_pressure_mean','engine_oil_pressure_mean_nz', ...
    'coolant_pressure_max','coolant_pressure_min','coolant_pressure_mean','coolant_pressure_mean_nz', ...
    'engine_crankcase_pressure_max','engine_crankcase_pressure_min','engine_crankcase_pressure_mean','engine_crankcase_pressure_mean_nz', ...
    'coolant_temperature_max','coolant_temperature_min','coolant_temperature_mean','coolant_temperature_mean_nz', ...
    'fuel_temperature_max','fuel_temperature_min','fuel_temperature_mean','fuel_temperature_mean_nz', ...
    'engine_oil_temperature_max','engine_oil_temperature_min','engine_oil_temperature_mean','engine_oil_temperature_mean_nz', ...
    'c1_power_steering_pressure_max','c1_power_steering_pressure_min','c1_power_steering_pressure_mean','c1_power_steering_pressure_mean_nz', ...
    'brake_pressure_front_max','brake_pressure_front_min','brake_pressure_front_mean','brake_pressure_front_mean_nz', ...
    'brake_pressure_rear_max','brake_pressure_rear_min','brake_pressure_rear_mean','brake_pressure_rear_mean_nz', ...
    'fuel_closed_loop_diagnostic_max','fuel_closed_loop_diagnostic_min','fuel_closed_loop_diagnostic_mean','fuel_closed_loop_diagnostic_mean_nz', ...
    'wheel_speed_front_left_max','wheel_speed_front_left_min','wheel_speed_front_left_mean','wheel_speed_front_left_mean_nz', ...
    'wheel_speed_front_right_max','wheel_speed_front_right_min','wheel_speed_front_right_mean','wheel_speed_front_right_mean_nz', ...
    'wheel_speed_rear_left_max','wheel_speed_rear_left_min','wheel_speed_rear_left_mean','wheel_speed_rear_left_mean_nz', ...
    'wheel_speed_rear_right_max','wheel_speed_rear_right_min','wheel_speed_rear_right_mean','wheel_speed_rear_right_mean_nz', ...
    'inlet_air_temp_mix_aim_max','inlet_air_temp_mix_aim_min','inlet_air_temp_mix_aim_mean','inlet_air_temp_mix_aim_mean_nz', ...
    'vcs_pit_entry_speed_max','vcs_pit_entry_speed_min','vcs_pit_entry_speed_mean','vcs_pit_entry_speed_mean_nz', ...
    'vcs_pit_exit_speed_max','vcs_pit_exit_speed_min','vcs_pit_exit_speed_mean','vcs_pit_exit_speed_mean_nz', ...
    'vcs_pit_sw_deact_exit_delta_d_max','vcs_pit_sw_deact_exit_delta_d_min','vcs_pit_sw_deact_exit_delta_d_mean','vcs_pit_sw_deact_exit_delta_d_mean_nz', ...
    'inlet_manifold_pressure_est_max','inlet_manifold_pressure_est_min','inlet_manifold_pressure_est_mean','inlet_manifold_pressure_est_mean_nz', ...
    'transmission_pressure_max','transmission_pressure_min','transmission_pressure_mean','transmission_pressure_mean_nz', ...
    'driver_pit_switch_max','driver_pit_switch_min','driver_pit_switch_mean','driver_pit_switch_mean_nz', ...
    'gps_sats_used_max','gps_sats_used_min','gps_sats_used_mean','gps_sats_used_mean_nz', ...
    'gps_altitude_max','gps_altitude_min','gps_altitude_mean','gps_altitude_mean_nz', ...
    'gps_latitude_max','gps_latitude_min','gps_latitude_mean','gps_latitude_mean_nz', ...
    'gps_longitude_max','gps_longitude_min','gps_longitude_mean','gps_longitude_mean_nz', ...
    'gps_heading_max','gps_heading_min','gps_heading_mean','gps_heading_mean_nz', ...
    'gps_time_max','gps_time_min','gps_time_mean','gps_time_mean_nz', ...
    'gps_date_max','gps_date_min','gps_date_mean','gps_date_mean_nz', ...
    'gps_speed_max','gps_speed_min','gps_speed_mean','gps_speed_mean_nz', ...
    'gps_valid_max','gps_valid_min','gps_valid_mean','gps_valid_mean_nz', ...
    'c1_damper_volts_fl_max','c1_damper_volts_fl_min','c1_damper_volts_fl_mean','c1_damper_volts_fl_mean_nz', ...
    'c1_damper_volts_fr_max','c1_damper_volts_fr_min','c1_damper_volts_fr_mean','c1_damper_volts_fr_mean_nz', ...
    'c1_damper_volts_rl_max','c1_damper_volts_rl_min','c1_damper_volts_rl_mean','c1_damper_volts_rl_mean_nz', ...
    'c1_damper_volts_rr_max','c1_damper_volts_rr_min','c1_damper_volts_rr_mean','c1_damper_volts_rr_mean_nz', ...
    'c1_susp_pos_fl_max','c1_susp_pos_fl_min','c1_susp_pos_fl_mean','c1_susp_pos_fl_mean_nz', ...
    'c1_susp_pos_fr_max','c1_susp_pos_fr_min','c1_susp_pos_fr_mean','c1_susp_pos_fr_mean_nz', ...
    'c1_susp_pos_rl_max','c1_susp_pos_rl_min','c1_susp_pos_rl_mean','c1_susp_pos_rl_mean_nz', ...
    'c1_susp_pos_rr_max','c1_susp_pos_rr_min','c1_susp_pos_rr_mean','c1_susp_pos_rr_mean_nz', ...
    'laps_since_pit_max','laps_since_pit_min','laps_since_pit_mean','laps_since_pit_mean_nz', ...
    'tpm1s_rr_ws_temp_max','tpm1s_rr_ws_temp_min','tpm1s_rr_ws_temp_mean','tpm1s_rr_ws_temp_mean_nz', ...
    'tpm1s_rr_ws_press_max','tpm1s_rr_ws_press_min','tpm1s_rr_ws_press_mean','tpm1s_rr_ws_press_mean_nz', ...
    'tpm1s_rl_ws_temp_max','tpm1s_rl_ws_temp_min','tpm1s_rl_ws_temp_mean','tpm1s_rl_ws_temp_mean_nz', ...
    'tpm1s_rl_ws_press_max','tpm1s_rl_ws_press_min','tpm1s_rl_ws_press_mean','tpm1s_rl_ws_press_mean_nz', ...
    'tpm1s_fr_ws_temp_max','tpm1s_fr_ws_temp_min','tpm1s_fr_ws_temp_mean','tpm1s_fr_ws_temp_mean_nz', ...
    'tpm1s_fr_ws_press_max','tpm1s_fr_ws_press_min','tpm1s_fr_ws_press_mean','tpm1s_fr_ws_press_mean_nz', ...
    'tpm1s_fl_ws_temp_max','tpm1s_fl_ws_temp_min','tpm1s_fl_ws_temp_mean','tpm1s_fl_ws_temp_mean_nz', ...
    'tpm1s_fl_ws_press_max','tpm1s_fl_ws_press_min','tpm1s_fl_ws_press_mean','tpm1s_fl_ws_press_mean_nz', ...
    'car_number_max','car_number_min','car_number_mean','car_number_mean_nz', ...
    'tpm1s_fl_ws_id_max','tpm1s_fl_ws_id_min','tpm1s_fl_ws_id_mean','tpm1s_fl_ws_id_mean_nz', ...
    'tpm1s_fr_ws_id_max','tpm1s_fr_ws_id_min','tpm1s_fr_ws_id_mean','tpm1s_fr_ws_id_mean_nz', ...
    'tpm1s_rl_ws_id_max','tpm1s_rl_ws_id_min','tpm1s_rl_ws_id_mean','tpm1s_rl_ws_id_mean_nz', ...
    'tpm1s_rr_ws_id_max','tpm1s_rr_ws_id_min','tpm1s_rr_ws_id_mean','tpm1s_rr_ws_id_mean_nz', ...
    'adr_acceleration_z_max','adr_acceleration_z_min','adr_acceleration_z_mean','adr_acceleration_z_mean_nz', ...
    'adr_acceleration_y_max','adr_acceleration_y_min','adr_acceleration_y_mean','adr_acceleration_y_mean_nz', ...
    'adr_acceleration_x_max','adr_acceleration_x_min','adr_acceleration_x_mean','adr_acceleration_x_mean_nz', ...
    'acceleration_x_filt_max','acceleration_x_filt_min','acceleration_x_filt_mean','acceleration_x_filt_mean_nz', ...
    'acceleration_y_filt_max','acceleration_y_filt_min','acceleration_y_filt_mean','acceleration_y_filt_mean_nz', ...
    'acceleration_z_filt_max','acceleration_z_filt_min','acceleration_z_filt_mean','acceleration_z_filt_mean_nz', ...
    'fuel_pressure_max','fuel_pressure_min','fuel_pressure_mean','fuel_pressure_mean_nz', ...
    'brakinggatevch_max','brakinggatevch_min','brakinggatevch_mean','brakinggatevch_mean_nz', ...
    'entrygatevch_max','entrygatevch_min','entrygatevch_mean','entrygatevch_mean_nz', ...
    'midcrngatevch_max','midcrngatevch_min','midcrngatevch_mean','midcrngatevch_mean_nz', ...
    'exitgatevch_max','exitgatevch_min','exitgatevch_mean','exitgatevch_mean_nz', ...
    'straightgatevch_max','straightgatevch_min','straightgatevch_mean','straightgatevch_mean_nz', ...
    'brakebiasvch_max','brakebiasvch_min','brakebiasvch_mean','brakebiasvch_mean_nz', ...
    'rl_slipvch_max','rl_slipvch_min','rl_slipvch_mean','rl_slipvch_mean_nz', ...
    'avgcrnvch_max','avgcrnvch_min','avgcrnvch_mean','avgcrnvch_mean_nz', ...
    'fl_locktimervch_max','fl_locktimervch_min','fl_locktimervch_mean','fl_locktimervch_mean_nz', ...
    'fr_locktimervch_max','fr_locktimervch_min','fr_locktimervch_mean','fr_locktimervch_mean_nz', ...
    'rl_locktimervch_max','rl_locktimervch_min','rl_locktimervch_mean','rl_locktimervch_mean_nz', ...
};

% ── Build fields array ───────────────────────────────────────
fields = cell(numel(txt_names) + numel(num_names), 1);
idx = 1;
for i = 1:numel(txt_names)
    fields{idx} = struct('name', txt_names{i}, 'type', 'text', 'required', false);
    idx = idx + 1;
end
for i = 1:numel(num_names)
    fields{idx} = struct('name', num_names{i}, 'type', 'number', 'required', false);
    idx = idx + 1;
end

fprintf('Total fields to create: %d\n', numel(fields));

% ── Build collection payload ─────────────────────────────────
col = struct();
col.name     = 'lap_stats';
col.type     = 'base';
col.fields   = {fields{:}};

json_str = jsonencode(col);

% ── POST to create collection ────────────────────────────────
create_body = StringProvider(json_str);
create_req  = RequestMessage('POST', ...
    [HeaderField('Content-Type','application/json'), ...
     HeaderField('Authorization', ['Bearer ' token])], ...
    create_body);
create_resp = create_req.send('http://127.0.0.1:8090/api/collections');
fprintf('Create status: %d\n', double(create_resp.StatusCode));

if double(create_resp.StatusCode) == 200 || double(create_resp.StatusCode) == 201
    fprintf('Collection created successfully with %d fields.\n', numel(fields));
else
    disp(create_resp.Body.Data)
end